dist: xenial

language: node_js

node_js:
  - '10'

cache:
  npm: true

install:
  - npm ci

script:
  - npm run lint

deploy:
  provider: npm
  email: $NPM_EMAIL_ADDRESS
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
